### ISSUE TITLE
System requirements to install spatial-correlation-sampler

### ISSUE THREAD

**Issue by phil-slz** [ClementPinard/Pytorch-Correlation-extension#84] opened 2021-11-24 15:05 UTC
I can't install the spatial-correlation-sampler on my remote gpu server.
I have the following constraints:

- Nvidia driver >= 460.27.03
- OS: Fedora release >= 32

Has someone successfully installed the sampler with these specs? 
If yes, which Python, torch, cuda, gcc and g++ versions are you using?
I have tried (not working) with:
- Python 3.9.7
- torch 1.9.0
- cuda 10.2
- gcc: 10.3.1
- g++: 10.3.1

**Comment by ClementPinard** [comment] 2023-05-24 19:50
Sorry for the lack of answer.

Closing it as it is too old for me to help you. Hope you were able to solve your problem or that with torch 2.0 you don't have this problem anymore

Feel free to reopen it if the problem is still here

**Closed by ClementPinard** 2023-05-24 19:50 UTC
